### ISSUE TITLE
Set up test runner, precommit, and linter

### ISSUE THREAD

**Issue by jrans** [dwyl/abase#22]
- [x] test runner
- [x] linter
- [x]  pre-commit 
- [x] istanbul

**Comment by nelsonic** [comment]
_linter_ ... 😉 

![apple-pie-from-scratch](https://cloud.githubusercontent.com/assets/194400/18760760/4fe15bd8-80fa-11e6-8eb3-37f8fa1a9a7e.png)

**Comment by samhstn** [comment]
#27 Addresses the pre-commit
