### ISSUE TITLE
Pushing to master github

### ISSUE THREAD

**Issue by samhstn** [dwyl/abase#28]
Currently we can push to master in this repo.

Can we configure this to be disallowed in the repo settings

**Comment by iteles** [comment]
@shouston3 Not sure what you're asking for here.
You currently have [write permissions](https://help.github.com/articles/repository-permission-levels-for-an-organization/) for this repo. Are you asking to be downgraded to read permissions? Pretty sure that wouldn't give you enough functionality.

Or are you asking specifically to not be able to push to master? In which case you're very welcome to google how and make it happen ;)

**Comment by iteles** [comment]
Ah, admin access. Done 👍 

As a note: this shouldn't be necessary, but not a battle worth spending time on right now!
