### ISSUE TITLE
Using Plugin inside Plugin

### ISSUE THREAD

**Issue by jrans** [dwyl/abase#32]
We'll be splitting work into multiple plugins, that may need to use each other. Whats the best practise?

Possible [answer](http://stackoverflow.com/questions/38591861/hapi-js-proper-way-to-include-a-plugin-inside-a-plugin)?

```
exports.register = function (server, options, next) {
  server.dependency('dwyl-pg-connection', function(server, next) {
    next();
  });
  next();
};
```

**Comment by samhstn** [comment]
I think modularising abase into multiple plugins which get registered is a good idea.

Possible sub plugins might be:

``` javascript
'abase-db'
'abase-routes'
'abase-validation'
'abase-render'
'abase-permissions'
```

As discussed in #50 by @eliascodes
