### ISSUE TITLE
Password Authentication with db

### ISSUE THREAD

**Issue by jrans** [dwyl/abase#53]
After #52 we need to check password plain text against the hash in db  with bcryot.compare to confirm the login. Be nice to make this general and provide nice methods config object to be interpreted

**Comment by nelsonic** [comment]
@jrans a `bcrypt` hash is _always_ different. which is what makes it _Strong_.
see: https://github.com/nelsonic/bcrypt#faq

Which means we cannot _compare_ two _hashed_ passwords, we _have_ to use `bcrypt.compare` which takes the plaintext and existing (_stored_) hash as inputs.
see: https://github.com/ncb000gt/node.bcrypt.js/#to-check-a-password

**Comment by jrans** [comment]
@nelsonic Yes realise. Old description was quick and inaccurate, updated now though.

**Comment by nelsonic** [comment]
Passwords will be hashed using `Argon2id` see: https://github.com/dwyl/fields/issues/13
