### ISSUE TITLE
Integration: SQL generation

### ISSUE THREAD

**Issue by eliasmalik** [dwyl/abase#56]
Integration of the SQL generation (see #31) into the [integration branch](https://github.com/dwyl/abase/tree/integration).

Primary job here is to substitute the spoofed DB operations from @SimonLab [endpoints-generator-2](https://github.com/dwyl/abase/tree/endpoints-generator-2) branch with real DB ops.

From inspecting the code, seems like [this](https://github.com/dwyl/abase/tree/endpoints-generator-2/lib/helpers/user) is the right place to put the SQL queries.

I obviously need to make the interface asynchronous, so may need to make some changes to the calling code as well.

@SimonLab comments welcome.

**Comment by SimonLab** [comment]
I've added these issues #59 #60 which details the config files and how to initialise the plugin. It might change a bit the way you are loading the fields for the database, let me know if this seems logic for you.

**Comment by eliasmalik** [comment]
Done in #64
