### ISSUE TITLE
Error handling joi validation

### ISSUE THREAD

**Issue by samhstn** [dwyl/abase#69]
Currently if there is a 400 error we display the error object on the page, this should be instead handled with an error message next to the field which is relevant to the error with the relevant error message

**Comment by nelsonic** [comment]
@shouston3 similar to how it's done in: https://github.com/dwyl/hapi-login-example-postgres ...?

**Comment by nelsonic** [comment]
Error handling will be done by a combination of [Fields](https://github.com/dwyl/fields) and [Autoform](https://github.com/dwyl/autoform).
