### ISSUE TITLE
SQL 'OR' queries

### ISSUE THREAD

**Issue by Danwhy** [dwyl/abase#73]
Is it possible to do OR (or AND) queries using this module at the moment?

For example:

`SELECT * FROM table WHERE id=1234 OR id=5678`

**Comment by jrans** [comment]
@Danwhy can you ask this question in https://github.com/dwyl/joi-postgresql as a feature request? (i.e. no but very happy for you to produce an elegant solution to add feature?

**Comment by Danwhy** [comment]
https://github.com/dwyl/joi-postgresql/issues/24
